name: maven-actions
on: push
jobs:
  confirm_build_passes:
    runs-on: ubuntu-latest
    steps:
       - name: Perform Java build on Linux
         run: |
           sudo apt-get install -y git openjdk-8-jdk maven
           git clone https://github.com/chocorho/speak-to-me-license
           echo "current directory is $(pwd)"
           cat pom.xml || echo "no pom file exists in this directory!!"
           echo "first java dir is $(find -name java | head -n 1)"
           (cd $(find -name java | head -n 1); mvn package)

