name: maven-actions
on: push
jobs:
  confirm_build_passes:
    runs-on: ubuntu-latest
    steps:
       - name: Perform Java build on Linux
         run: |
           apt-get install openjdk-8-jdk
           cd java && mvn package

